<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SalesArena.Replay.Podcast</RootNamespace>
    <AssemblyName>SalesArena.Replay.Podcast</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SalesArena.Replay.csproj" />
  </ItemGroup>
</Project>
