using System.Text;
using SalesArena.Orchestrator.Ledger;
using SalesArena.Replay.Sections.Roast;

namespace SalesArena.Replay.Sections;

/// <summary>
/// "🔥 The Roast" — an end-of-contest comedy section where higher-ranked
/// personas critique lower-ranked ones in their own voice. Hallucination-
/// guarded: every paragraph must cite real events from the target's contest
/// log or the section refuses to ship that paragraph.
///
/// <para>Pairs are generated by walking the final leaderboard top-down:
/// position 1 roasts position 2, position 2 roasts position 3, and so on.
/// Sole-persona contests render a "no roast partner" footer.</para>
/// </summary>
public sealed class RoastSectionBuilder : ISectionBuilder
{
    private readonly IRoastWriter _writer;

    public RoastSectionBuilder(IRoastWriter? writer = null)
    {
        _writer = writer ?? new StubRoastWriter();
    }

    public ReplaySectionKind Kind => ReplaySectionKind.Roast;

    public async Task<SectionResult> BuildAsync(SectionContext ctx, CancellationToken cancellationToken = default)
    {
        var sb = new StringBuilder();
        sb.AppendLine(TemplateLoader.LoadHeader(Kind, ctx));
        sb.AppendLine();

        if (ctx.FinalLeaderboard.Entries.Count < 2)
        {
            sb.AppendLine("*Need at least 2 personas for a roast — solo runs don't get the mic.*");
            var emptyResult = new ReplaySection(Kind, "The Roast", sb.ToString().TrimEnd());
            return Task.FromResult(new SectionResult(emptyResult, Array.Empty<ReplayHighlight>())).Result;
        }

        var highlights = new List<ReplayHighlight>();
        var entries = ctx.FinalLeaderboard.Entries;
        var roastsRendered = 0;

        for (var i = 0; i < entries.Count - 1; i++)
        {
            var roaster = entries[i].Persona;
            var target = entries[i + 1].Persona;
            var targetEvents = ctx.AllEvents
                .Where(e => string.Equals(e.Persona, target, StringComparison.Ordinal))
                .ToList();

            var raw = await _writer.WriteRoastAsync(roaster, target, targetEvents, cancellationToken).ConfigureAwait(false);
            var guard = RoastHallucinationGuard.Verify(raw, targetEvents);
            if (!guard.IsOk)
            {
                sb.AppendLine($"*[Roast from **{roaster}** withheld: {guard.Reason}.]*");
                sb.AppendLine();
                continue;
            }

            sb.AppendLine($"**{roaster}** on **{target}:**");
            sb.AppendLine();
            sb.AppendLine(raw);
            sb.AppendLine();
            roastsRendered++;

            highlights.Add(new ReplayHighlight(
                Source: Kind,
                Headline: $"{roaster} roasts {target}.",
                Persona: roaster,
                LeadId: null,
                ValueUsd: null,
                OccurredAtUtc: ctx.GeneratedAtUtc));
        }

        if (roastsRendered == 0)
        {
            sb.AppendLine("*All roasts were withheld by the hallucination guard.*");
        }

        var section = new ReplaySection(Kind, "The Roast", sb.ToString().TrimEnd());
        return new SectionResult(section, highlights);
    }
}
